In [52]:
import pandas as pd
import numpy as np
print(pd.__version__)
print(pd.options.display.max_rows)
pd.set_option("display.max_columns", None)  # print all columns of a dataframe; we can replace "None" by any number if we want to print a certain number of columns
pd.set_option("max_colwidth", None)   # Set the Column Width.
pd.set_option("display.max_rows", 100)

2.0.3
100

# 1. Reduce the size of dataset by removing duplicates

In [ ]:
### Generate the processed data with no duplicates for the official fuel efficiency data from 2015 to 2023. ###
# Windows
df15 = pd.read_csv("C:/Users/uctpql0/OneDrive - University College London/Cars data/data/raw data/official fuel efficiency/2015_fe.csv", low_memory=False)
df16 = pd.read_csv("C:/Users/uctpql0/OneDrive - University College London/Cars data/data/raw data/official fuel efficiency/2016_fe.csv", low_memory=False)
df17 = pd.read_csv("C:/Users/uctpql0/OneDrive - University College London/Cars data/data/raw data/official fuel efficiency/2017_fe.csv", low_memory=False)
df18 = pd.read_csv("C:/Users/uctpql0/OneDrive - University College London/Cars data/data/raw data/official fuel efficiency/2018_fe.csv", low_memory=False)
df19 = pd.read_csv("C:/Users/uctpql0/OneDrive - University College London/Cars data/data/raw data/official fuel efficiency/2019_fe.csv", low_memory=False)
df20 = pd.read_csv("C:/Users/uctpql0/OneDrive - University College London/Cars data/data/raw data/official fuel efficiency/2020_fe.csv", low_memory=False)
df21 = pd.read_csv("C:/Users/uctpql0/OneDrive - University College London/Cars data/data/raw data/official fuel efficiency/2021_fe.csv", low_memory=False)
df22 = pd.read_csv("C:/Users/uctpql0/OneDrive - University College London/Cars data/data/raw data/official fuel efficiency/2022_fe.csv", low_memory=False)
df23 = pd.read_csv("C:/Users/uctpql0/OneDrive - University College London/Cars data/data/raw data/official fuel efficiency/2023_fe.csv", low_memory=False)

for df in [df15, df16, df17, df18, df19, df20, df21, df22, df23]:
    
    df.columns = df.columns.str.lower()  # convert column names to lowercase
    df.drop(columns='id', inplace=True)  # drop the 'id' column, otherwise there will be no duplicates
    
    valid_columns = df.columns[df.notnull().any()]    # pick columns that have at least one non-null value
    valid_columns = valid_columns[valid_columns.get_loc('country'):valid_columns.get_loc('cn')+1]  # pick columns that are needed to identify duplicates: from country to commercial name ! 
    df['duplicate_count'] = df.groupby(valid_columns.tolist(), dropna=False).transform('size')  # count the number of duplicates based on the selected columns, remember to include 'dropna=False' to deal with NaN values, otherwise, there will be NaN in the 'duplicate_count' column.
    
    df.drop_duplicates(subset=valid_columns.tolist(), keep = 'first', inplace=True)   # only keep the first occurrence of each duplicate, drop the rest
    df['sales'] = df['duplicate_count'] * df['r']   # calculate the total sales for each car model, NB. data from 2015 to 2019 have multiple values of 'r'

    df.to_csv(f"C:/Users/uctpql0/OneDrive - University College London/Cars data/data/processed data/official fuel efficiency/{df['year'].iloc[0]}_fe_all_nodup.csv", index=False)  # save as csv file

### combine data from 2015 to 2023
df_combined = pd.concat([df15, df16, df17, df18, df19, df20, df21, df22, df23], ignore_index=True)
df_combined.to_csv("C:/Users/uctpql0/OneDrive - University College London/Cars data/data/processed data/official fuel efficiency/2015_2023_fe_all_nodup.csv", index=False)  # save as csv file

Some observations:
1. rows with same 'country' to 'cn' have different characteristics in different years.
2. rows with same 'vfn' to 'cn' and 'year' have different characteristics in different country!

In [116]:
# Mac
df = pd.read_csv("/Users/simon/Library/CloudStorage/OneDrive-UniversityCollegeLondon/Cars data/data/processed data/official fuel efficiency/2015_2023_fe_all_nodup.csv", low_memory=False)
# Windows
#df = pd.read_csv("C:/Users/uctpql0/OneDrive - University College London/Cars data/data/processed data/official fuel efficiency/2015_2023_fe_all_nodup.csv", low_memory=False)

# 2. Generate the parent name for each manufacturer

This is the instruction for Grok 3 to match manufacture from parent company name:
1. upload two files:
    1) potential list txt    # contains the unique values of 'parent' in the sales dataset.
    2) manufacturers. xlsx   # contains the unique values of 'mh' in the official emission dataset
2. for each manufacturer in the "manufacturer.xlsx" file, search online and fill in its parent company name by first choosing from
    1) all potential company names in the "potential list"
    2) if you can't find a suitable one from the "potential list.text", fill in what you find in the internet.
3. add one column showing whether the correct parent name is taken from the potential list, or from the web-sourced data
4. can you generate an excel file of the above content?

In [ ]:
### Further generate a parent name for the rows with weird 'mh' values

df['mh'] = df['mh'].str.strip() # remove leading and trailing whitespaces
# OUT OF SCOPE: 9447
#df[df['mh'].str.contains('scope', case=False, na=False)]   # for those 'mh'=='OUT OF SCOPE', determine their parent by looking at 'mms'
# UNKNOWN: 1742
#df[df['mh'].str.contains('UNKNOWN', case=False, na=False)]  
# AA-IVA: 50939
#df[df['mh'].str.contains('AA-IVA', case=False, na=False)]
# AA-NSS: 558
#df[df['mh'].str.contains('AA-NSS', case=False, na=False)]
# MICRO VETT: 2
#df[df['mh'].str.contains('MICRO VETT', case=False, na=False)]
# ADIDOR: 26
#df[df['mh'].str.contains('ADIDOR', case=False, na=False)]
# TAIQI: 1
#df[df['mh'].str.contains('TAIQI', case=False, na=False)]
# TECNO MECCANICA: 7
#df[df['mh'].str.contains('TECNO MECCANICA', case=False, na=False)]
# BEE BEE: 2
#df[df['mh'].str.contains('BEE BEE', case=False, na=False)]
# FSO: 1
#df[df['mh'].str.contains('FSO', case=False, na=False)]
# LANZHOU ZHIDOU: 2
#df[df['mh'].str.contains('LANZHOU ZHIDOU', case=False, na=False)]
# HENAN SUDA: 13
#df[df['mh'].str.contains('HENAN SUDA', case=False, na=False)]
# LANZHOU: 49
#df[df['mh'].str.contains('LANZHOU', case=False, na=False)]
# NANJING GOLDEN DRAGON: 19
#df[df['mh'].str.contains('NANJING GOLDEN DRAGON', case=False, na=False)]
# LEEH: 2
#df[df['mh'].str.contains('LEEH', case=False, na=False)]
# ZHAOQING: 63
#df[df['mh'].str.contains('ZHAOQING', case=False, na=False)]
# EURASIA: 8
#df[df['mh'].str.contains('EURASIA', case=False, na=False)]
# YUDO AUTO: 2
#df[df['mh'].str.contains('YUDO AUTO', case=False, na=False)]
# ZHEJIANG HAOQING: 2
#df[df['mh'].str.contains('ZHEJIANG', case=False, na=False)]

# select MAZADA by keyword 'mazada'

In [117]:
# load the second sheet of the excel file, 
dm  = pd.read_excel('/Users/simon/Library/CloudStorage/OneDrive-UniversityCollegeLondon/Cars data/Parent company.xlsx', sheet_name='Match')
# add a column 'parent' to df. For each 'mh' in df, find the corresponding 'parent' in dm
df['parent'] = df['mh'].map(dm.set_index('manufacturer')['parent'])

# df['parent'].nunique()  # 63 unique parent

# 3. Keep only passenger cars

In [118]:
# Generate a column 'vehicle type' whose values depend on the values of 'ct' and 'cr':
# 1) if 'cr' or 'ct' contains values in ['M1S', 'M2', 'N1', 'N1G', 'N2','N2G','N3G','N3'], then vehicle type is 'commercial car';
# 2) otherwise, the vehicle type is 'unknown'
df['vehicle type'] = np.where(df['cr'].str.contains('M1S|M2|N1|N1G|N2|N2G|N3G|N3', na=False) | df['ct'].str.contains('M1S|M2|N1|N1G|N2|N2G|N3G|N3', na=False), 'commercial car', 'unknown')   # take care of nan values
# 3) among rows whose 'vehicle type is 'unknown', change the vehicle type to 'passenger car' if its of 'cr' and 'ct' contains values in ['M1', 'M1S]
df.loc[(df['vehicle type'] == 'unknown') & (df['cr'].str.contains('M1|M1S', na=False) | df['ct'].str.contains('M1|M1S', na=False)), 'vehicle type'] = 'passenger car'   # take care of nan values
# only keep rows whose 'vehicle type' is 'passenger car'
df = df[df['vehicle type'] == 'passenger car']

# df['parent'].nunique()  # 62 unique parent

Before deleting commericial cars and unknowns:
1) 189 manucfacturers
2) 1,094 makes
3) 48,254 Car commercial names

After only keeping passenger cars
1) 188 manucfacturers
2) 1,086 makes
3) 48,170 Car commercial names

# 4. Simplify Brand names

In [ ]:
### Miscellaneous
# rename the column 'mk' to 'brand'
df.rename(columns={'mk': 'brand'}, inplace=True)
# load the excel file generated from sales data that contains the mapping between brand name in sales dataset and emission dataset
dmatch = pd.read_excel('/Users/simon/Library/CloudStorage/OneDrive-UniversityCollegeLondon/Cars data/brand_keyword.xlsx', sheet_name='Sheet2')
# change the data type of 'brand' and 'keywords' to string
dmatch['brand'] = dmatch['brand'].astype(str)
dmatch['keywords'] = dmatch['keywords'].astype(str)
# strip the values in 'brand' to remove leading and trailing whitespaces and change it to lowercase
df['brand'] = df['brand'].str.strip().str.lower()
# truncate the dataset to only include the columns 'brand' and 'keywords'
dmatch = dmatch[['brand', 'keywords']]

### For data before 'Ford', use for-loop to match
dmatch_loop = dmatch.iloc[:dmatch[dmatch['brand'] == 'Ford'].index[0]]
# for each row in df, replace its 'brand' with the 'brand' in dmatch according to the 'keywords' in dmatch
for index, row in dmatch_loop.iterrows():
    df.loc[df['brand'].str.contains(row['keywords'], case=False, na=False), 'brand'] = row['brand']

### For data after 'Ford', use manual matching
# select ford 
df.loc[(df['brand'].str.contains('ford', na=False))& (df['brand']!='aveling barford'), 'brand'] = 'Ford'
# select mg
df.loc[(df['brand'].str.contains('mg', na=False))& (df['brand']!='made4mg')& (df['brand']!='r1eamg')& (~df['brand'].str.contains('merc', na=False)), 'brand'] = 'MG'
# select fiat
df.loc[(df['brand'].str.contains('fiat', na=False))& (df['brand']!='iveco-fiat')& (df['brand']!='dodge fiat'), 'brand'] = 'Fiat'
# select porsche
df.loc[(df['brand'].str.contains('porsche', na=False))& (df['brand']!='audiporsche'), 'brand'] = 'Porsche'
# select ds
df.loc[(df['brand']=='ds') | (df['brand']=='ds automobiles'), 'brand'] = 'DS'

### 打补丁(there are many more, look for them when you have time!)
df.loc[(df['brand'].str.contains('jeep', na=False)), 'brand'] = 'Jeep'   # why it doesn't work in for loop?
df.loc[(df['brand'].str.contains('opel', na=False))& (df['brand']!='aveling barford'), 'brand'] = 'Opel-Vauxhall'
df.loc[(df['brand'].str.contains('suzu', na=False))& (df['brand']!='aveling barford'), 'brand'] = 'Suzuki'
df.loc[(df['brand'].str.contains('erc', na=False))& (df['brand']!='mercus')& (df['brand']!='vipercobra'), 'brand'] = 'Mercedes-Benz'
#df.loc[(df['brand'].str.contains('', na=False)), 'brand'] = 'Mercedes-Benz'
#df.loc[(df['brand'].str.contains('', na=False)), 'brand'] = 'Mercedes-Benz'
df.loc[(df['brand'].str.contains('koda', na=False)), 'brand'] = 'Skoda'
df.loc[(df['brand'].str.contains('volk', na=False)), 'brand'] = 'Volkswagen'
df.loc[(df['brand'].str.contains('alpin', na=False)), 'brand'] = 'Alpine'

In [ ]:
# save the result (Mac)
df.to_csv("/Users/simon/Library/CloudStorage/OneDrive-UniversityCollegeLondon/Cars data/data/processed data/official fuel efficiency/2015_2023_fe_all_nodup_passenger_car_with_parent_simplified_brand.csv", index=False)

# 5. Using Grok 3 to fill in body type

In [ ]:
### create the file to throw into the LLMs to get the body type information
# only keep rows whose 'mk' is in 'brand' column of dmatch
dmatch = pd.read_excel('/Users/simon/Library/CloudStorage/OneDrive-UniversityCollegeLondon/Cars data/brand_keyword.xlsx', sheet_name='Sheet2')
df = df[df['brand'].isin(dmatch['brand'])]
# replace ',' in 'cn' with '.' This is important for creating the CSV file correctly!
df['cn'] = df['cn'].str.replace(',', '.')
# create unique combination of 'brand' and 'cn'
df_unique = df[['brand', 'cn']].drop_duplicates()
# select rows whose 'brand' and 'cn' is not null
df_unique = df_unique[df_unique['brand'].notnull() & df_unique['cn'].notnull()]  # 41551 rows
# create an excel file that contains the unique combination of 'brand' and 'cn'
df_unique.to_excel('/Users/simon/Library/CloudStorage/OneDrive-UniversityCollegeLondon/Cars data/LLMs/unique_brand_cn.xlsx', index=False)

Prompt for LLMs: fill in the body type of row with ID 1-41551, based on its brand and commercial name, create a csv file for it.

# 6. Match body type to emission dataset

In [126]:
# Load csv file
# Mac
df = pd.read_csv("/Users/simon/Library/CloudStorage/OneDrive-UniversityCollegeLondon/Cars data/data/processed data/official fuel efficiency/2015_2023_fe_all_nodup_passenger_car_with_parent_simplified_brand.csv", low_memory=False)
# Windows
#df = pd.read_csv("C:/Users/uctpql0/OneDrive - University College London/Cars data/data/processed data/official fuel efficiency/2015_2023_fe_all_nodup_passenger_car_with_parent_simplified_brand.csv", low_memory=False)

In [ ]:
# replace ',' in 'cn' with '.' This is important for creating the CSV file correctly!
df['cn'] = df['cn'].str.replace(',', '.')
# select those rows whose 'enedc (g/km)' and 'ewltp (g/km)' are not both null
df_select = df[df['enedc (g/km)'].notnull() | df['ewltp (g/km)'].notnull()]    # 62 unique parents
# load the sales data
ds = pd.read_csv('/Users/simon/Library/CloudStorage/OneDrive-UniversityCollegeLondon/Cars data/data/processed data/sales/2015_2023_sales_aggregate.csv', low_memory=False)
# select those rows whose 'parent' is in ds_parent
ds_parent = ds['parent'].unique()   # 43 unique parent

#df_select = df_select[df_select['parent'].isin(ds_parent)]
#df_select['parent'].nunique()  # 62 unique parent

In [ ]:
### reduce the size of the dataset by:
#1) selecting only those rows whose 'enedc (g/km)' and 'ewltp (g/km)' are not both null
#2) selecting only those rows whose 'parent' is in ds_parent
#3) selecting only those rows whose 'brand' is in ds_brand

# replace ',' in 'cn' with '.' This is important for creating the CSV file correctly!
df['cn'] = df['cn'].str.replace(',', '.')
# select those rows whose 'enedc (g/km)' and 'ewltp (g/km)' are not both null
df_select = df[df['enedc (g/km)'].notnull() | df['ewltp (g/km)'].notnull()]    # 62 unique parents

# load the sales data
ds = pd.read_csv('/Users/simon/Library/CloudStorage/OneDrive-UniversityCollegeLondon/Cars data/data/processed data/sales/2015_2023_sales_aggregate.csv', low_memory=False)
# select those rows whose 'parent' is in ds_parent
ds_parent = ds['parent'].unique()
df_select = df_select[df_select['parent'].isin(ds_parent)]   # This step reduce the number of unique parent from 62 to 43 !
# select those rows whose 'brand' is in ds_brand
ds_brand = ds['brand'].unique()
df_select = df_select[df_select['brand'].isin(ds_brand)]   
# df_select.shape  # 3,070,410 observations

# df_select['parent'].nunique()  # 33 unique parent, why it reduces so much?

In [ ]:
### Match body type (1-step version)
# load the match data (Mac)
dmatch = pd.read_excel('/Users/simon/Library/CloudStorage/OneDrive-UniversityCollegeLondon/Cars data/LLMs/Match/combine_output.xlsx')
# add a column 'body type' to  df_select whose values depend on the values of 'brand' and 'cn' according to dmatch (754 mins!)
df_select['body type'] = df_select.apply(lambda x: dmatch[(dmatch['brand'] == x['brand']) & (dmatch['cn'] == x['cn'])]['body type'].values[0] if dmatch[(dmatch['brand'] == x['brand']) & (dmatch['cn'] == x['cn'])].shape[0] > 0 else 'unknown', axis=1)
# save the full matched result
df_select.to_csv("/Users/simon/Library/CloudStorage/OneDrive-UniversityCollegeLondon/Cars data/data/processed data/official fuel efficiency/2015_2023_fe_all_nodup_passenger_car_with_parent_simplified_brand_body_type_full_match.csv", index=False)

In [ ]:

### Match body type (2-step version)
# load the partial matched result (Mac)
df_body = pd.read_csv("/Users/simon/Library/CloudStorage/OneDrive-UniversityCollegeLondon/Cars data/data/processed data/official fuel efficiency/2015_2023_fe_all_nodup_passenger_car_with_parent_simplified_mk_body_type_partial_match.csv", low_memory=False)

#rename column 'mk' to 'brand'
df_body.rename(columns={'mk': 'brand'}, inplace=True)
# select those rows whose 'enedc (g/km)' and 'ewltp (g/km)' are not both null
df_body_select = df_body[df_body['enedc (g/km)'].notnull() | df_body['ewltp (g/km)'].notnull()]
# select those rows whose 'parent' is in ds_parent
df_body_select = df_body_select[df_body_select['parent'].isin(ds_parent)]
# select those rows whose 'brand' is in ds_brand
df_body_select = df_body_select[df_body_select['brand'].isin(ds_brand)]   
df_body_select.shape  # 3,070,410 observations

### Replace the values of 'body type' in df_body_select for rows whose 'body type' equal 'unknown': 
mask = df_body_select['body type'] == 'unknown'
df_body_select.loc[mask, 'body type'] = df_body_select[mask].apply(
    lambda x: dmatch[(dmatch['brand'] == x['brand']) & (dmatch['cn'] == x['cn'])]['body type'].values[0] 
    if dmatch[(dmatch['brand'] == x['brand']) & (dmatch['cn'] == x['cn'])].shape[0] > 0 
    else 'unknown', 
    axis=1)
# save the full matched result
df_body_select.to_csv("/Users/simon/Library/CloudStorage/OneDrive-UniversityCollegeLondon/Cars data/data/processed data/official fuel efficiency/2015_2023_fe_all_nodup_passenger_car_with_parent_simplified_brand_body_type_full_match.csv", index=False)

# 7. Aggregate Emission data

In [36]:
### load data
# Mac
df = pd.read_csv("/Users/simon/Library/CloudStorage/OneDrive-UniversityCollegeLondon/Cars data/data/processed data/official fuel efficiency/2015_2023_fe_all_nodup_passenger_car_with_parent_simplified_brand_body_type_full_match.csv", low_memory=False)
# Windows
#df = pd.read_csv("C:/Users/uctpql0/OneDrive - University College London/Cars data/data/processed data/official fuel efficiency/2015_2023_fe_all_nodup_passenger_car_with_parent_simplified_brand_body_type_full_match.csv", low_memory=False)

In [37]:
### 1. rename some of the body type: 
# Coupe as Car;
df['body type'] = df['body type'].replace('Coupe','Car')
#Sedan: Car;
df['body type'] = df['body type'].replace('Sedan','Car')
#Hatchback: Car;
df['body type'] = df['body type'].replace('Hatchback','Car')
#Coupe suv: SUV;
df['body type'] = df['body type'].replace('Coupe SUV','SUV')
#Crossover: SUV;
df['body type'] = df['body type'].replace('Crossover','SUV')
#H hatchback: Hatchback;
df['body type'] = df['body type'].replace('H Hatchback','Car')
#Minivan: MPV;
df['body type'] = df['body type'].replace('Minivan','MPV')
#Station wagon: Wagon;
df['body type'] = df['body type'].replace('Station Wagon','Wagon')

In [38]:
### 2. Rename fuel type
# rename 'ft' to 'fuel type'
df.rename(columns={'ft': 'fuel type'}, inplace=True)
df['fuel type'] = df['fuel type'].str.lower()
df['fuel type'] = df['fuel type'].str.rstrip()
df['fuel type'] = df['fuel type'].str.lstrip()

# for rows with 'cn' containing 'plug' (ignoring case), replace its value in 'fuel type' by 'phev'
df.loc[df['cn'].str.contains('plug', case=False, na=False), 'fuel type'] = 'phev'
# for rows with 'cn' containing 'hybrid' (ignoring case), replace its value in 'fuel type' by 'hybrid'
df.loc[df['cn'].str.contains('hybrid', case=False, na=False), 'fuel type'] = 'hybrid'

# rename the values in 'fuel type' column
df['fuel type'] = df['fuel type'].replace('lpg','alternative_fuel')
df['fuel type'] = df['fuel type'].replace('ng-biomethane','alternative_fuel')
df['fuel type'] = df['fuel type'].replace('ng_biomethane','alternative_fuel')
df['fuel type'] = df['fuel type'].replace('e85','alternative_fuel')
df['fuel type'] = df['fuel type'].replace('biodiesel','alternative_fuel')
df['fuel type'] = df['fuel type'].replace('petrol-electric','phev')
df['fuel type'] = df['fuel type'].replace('hydrogen','alternative_fuel')
df['fuel type'] = df['fuel type'].replace('diesel-electric','phev')
df['fuel type'] = df['fuel type'].replace('petrol-gas','alternative_fuel')
df['fuel type'] = df['fuel type'].replace('hybrid/petrol/e','hybrid')      # not enough hybrid cars!?
df['fuel type'] = df['fuel type'].replace('petrol phev', 'phev')   #
df['fuel type'] = df['fuel type'].replace('petrol/electric','phev')
df['fuel type'] = df['fuel type'].replace('diesel/electric','phev')
df['fuel type'] = df['fuel type'].replace('ng','alternative_fuel')    # natural gas
df['fuel type'] = df['fuel type'].replace('cng','alternative_fuel')    # compressed natural gas
df['fuel type'] = df['fuel type'].replace('gnl','ice')    # gasoline
df['fuel type'] = df['fuel type'].replace('diesel','ice')
df['fuel type'] = df['fuel type'].replace('petrol','ice')
df['fuel type'] = df['fuel type'].replace('electric','bev')

In [39]:
### 3. rename columns names: ewltp (g/km) to wltp; enedc (g/km) to nedc; m (kg) to mass; mt to mass_wltp; ep (kw) to power; ec (cm3) to capacity; electric range (km) to range
df.rename(columns={'ewltp (g/km)': 'wltp', 'enedc (g/km)': 'nedc', 
                   'm (kg)': 'mass', 
                   'mt': 'mass_wltp', 
                   'ep (kw)': 'power', 
                   'ec (cm3)': 'capacity', 
                   'electric range (km)': 'range'}, inplace=True)

In [40]:
df

,country,vfn,mp,mh,man,mms,tan,t,va,ve,brand,cn,ct,cr,r,mass,mass_wltp,nedc,wltp,w (mm),at1 (mm),at2 (mm),fuel type,fm,capacity,power,z (wh/km),it,ernedc (g/km),erwltp (g/km),de,vf,status,year,date of registration,fuel consumption,ech,rlfi,range,duplicate_count,sales,duplicate,parent,vehicle type,body type
0,GB,NaN,VW GROUP PC,VOLKSWAGEN,VOLKSWAGEN AG,VOLKSWAGEN,e1*2001/116*0471*20,13,ADCUUB,FM6FM62Q0257MMVR2N1RL62,Volkswagen,SCIROCCO BLUEMOTION TECH TDI,M1,NaN,5.0,1375.0,NaN,109.0,NaN,2575.0,1552.0,1558.0,ice,M,1968.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F,2015.0,NaN,NaN,NaN,NaN,NaN,1.0,5.0,2,Volkswagen,passenger car,Car
1,GB,NaN,VW GROUP PC,VOLKSWAGEN,VOLKSWAGEN AG,VOLKSWAGEN,e1*2001/116*0471*20,13,ADCUWA,FM6FM6FB0017MMVR2N1RL62,Volkswagen,SCIROCCO GT BLUEMOTN TECH TDI,M1,NaN,3.0,1395.0,NaN,115.0,NaN,2575.0,1552.0,1558.0,ice,M,1968.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F,2015.0,NaN,NaN,NaN,NaN,NaN,1.0,3.0,2,Volkswagen,passenger car,Car
2,GB,NaN,VW GROUP PC,VOLKSWAGEN,VOLKSWAGEN AG,VOLKSWAGEN,e1*2001/116*0510*21,6R,ABCUSB,FM5FM5A4054N2VR27MM,Volkswagen,POLO SEL TDI,M1,NaN,8.0,1151.0,NaN,88.0,NaN,2456.0,1441.0,1434.0,ice,M,1422.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F,2015.0,NaN,NaN,NaN,NaN,NaN,1.0,8.0,1,Volkswagen,passenger car,Car
3,GB,NaN,VW GROUP PC,VOLKSWAGEN,VOLKSWAGEN AG,VOLKSWAGEN,e1*2001/116*0510*22,6R,ABCHYA,FM5FM5CF007N3VR27MM,Volkswagen,POLO SE,M1,NaN,200.0,1055.0,NaN,106.0,NaN,2456.0,1441.0,1434.0,ice,M,999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F,2015.0,NaN,NaN,NaN,NaN,NaN,1.0,200.0,1,Volkswagen,passenger car,Car
4,GB,NaN,VW GROUP PC,VOLKSWAGEN,VOLKSWAGEN AG,VOLKSWAGEN,e1*2001/116*0510*22,6R,ABCJZC,FM5FM52T106N2VR27MM,Volkswagen,POLO SE TSI,M1,NaN,1043.0,1107.0,NaN,107.0,NaN,2456.0,1441.0,1434.0,ice,M,1197.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F,2015.0,NaN,NaN,NaN,NaN,NaN,1.0,1043.0,1,Volkswagen,passenger car,Car
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3070405,PT,IP-0000925_UWBA,BMW,BMW AG,BAYERISCHE MOTOREN WERKE AG,NaN,e1*2018/858*00153*04,U1X,11EE,EAH500L0,BMW,X1 sDrive 18i,M1,M1,1.0,1575.0,1657.0,NaN,144.0,NaN,NaN,NaN,ice,M,1499.0,100.0,NaN,e24 29 37,NaN,2.13,NaN,NaN,P,2023.0,2023-12-28,6.4,NaN,NaN,NaN,1.0,1.0,1,BMW,passenger car,SUV
3070406,PT,IP-0120-JT1-1,SUBARU-SUZUKI-TOYOTA,TOYOTA,TOYOTA MOTOR EUROPE NV SA,NaN,e6*2007/46*0429*02,XA5P(EU M),AXAP54(N),AXAP54L-ANXGBW(2C),Toyota,TOYOTA RAV4,M1,M1,1.0,2005.0,2162.0,NaN,22.0,NaN,NaN,NaN,phev,P,2487.0,136.0,166.0,NaN,NaN,NaN,NaN,NaN,P,2023.0,2023-09-01,1.0,NaN,NaN,75.0,1.0,1.0,1,Toyota,passenger car,SUV
3070407,PT,IP-0200-JT1-1,SUBARU-SUZUKI-TOYOTA,TOYOTA,TOYOTA MOTOR EUROPE NV SA,NaN,e6*2007/46*0318*07,ZE1HE(EU M),ZWE219(H),ZWE219L-DHXNBW(2H),Toyota,TOYOTA COROLLA,M1,M1,1.0,1420.0,1511.0,NaN,104.0,NaN,NaN,NaN,ice,H,1798.0,72.0,NaN,e6 37,NaN,0.60,NaN,NaN,P,2023.0,2023-10-31,4.6,NaN,NaN,NaN,1.0,1.0,1,Toyota,passenger car,Car
3070408,PT,IP-C482_2021_00004-WF0-1,FORD,FORD WERKE GMBH,FORD-WERKE GMBH,NaN,e13*2007/46*2188*13,DFK,BGDA1FX,566DANA51,Ford,KUGA,M1,M1,1.0,1844.0,1926.0,NaN,22.0,NaN,NaN,NaN,phev,P,2488.0,112.0,146.0,NaN,NaN,NaN,NaN,NaN,P,2023.0,2023-11-29,1.0,NaN,NaN,65.0,2.0,2.0,1,Ford,passenger car,SUV
3070409,PT,IP-0200-JT1-1,SUBARU-SUZUKI-TOYOTA,TOYOTA,TOYOTA MOTOR EUROPE NV SA,NaN,e6*2007/46*0318*07,ZE1HE(EU M),ZWE219(W),ZWE219L-DWXSBW(1H),Toyota,TOYOTA COROLLA,M1,M1,1.0,1475.0,1569.0,NaN,107.0,NaN,NaN,NaN,ice,H,1798.0,72.0,NaN,e6 37,NaN,0.60,NaN,NaN,P,2023.0,2023-12-14,4.7,NaN,NaN,NaN,1.0,1.0,1,Toyota,passenger car,Car

In [41]:
### 4.aggregate the data based on 'parent', 'brand', 'body type', 'fuel type', calculate the associated emissions level, range (if electric) for each combination.
# Group the data
df = df.groupby(['parent', 'brand', 'body type', 'fuel type']).agg({
    'wltp' : 'mean',      # for car characteristics, take the mean of different trims
    'nedc' : 'mean',
    'power' : 'mean', 
    'capacity' : 'mean', 
    'mass' : 'mean',  
    'mass_wltp' : 'mean',
    'range' : 'mean'
}).round(2).copy()
df = df.reset_index()   # Reset the index to make the groupby columns back to columns

In [ ]:
# Save the data
df.to_csv("/Users/simon/Library/CloudStorage/OneDrive-UniversityCollegeLondon/Cars data/data/processed data/official fuel efficiency/2015_2023_fe_aggregate.csv", index=False)
# load the data
# Mac
df = pd.read_csv("/Users/simon/Library/CloudStorage/OneDrive-UniversityCollegeLondon/Cars data/data/processed data/official fuel efficiency/2015_2023_fe_aggregate.csv", low_memory=False)

In [ ]:
# rename the column names
df = df.rename(columns={'VFN':'Vehicle family identification number', 'Mp':'Manufacturer pooling','Mh':'Manufacturer name EU standard denomination',
                        'Man':'Manufacturer name OEM declaration','MMS':'Manufacturer name MS registry denomination','Tan':'Type approval number',
                        'T':'Type','Va':'Variant','Ve':'Version',
                        'Mk':'Make','Cn':'Commercial name','Ct':'Category of the vehicle type approved',
                        'Cr':'Category of the vehicle registered','r':'Total new registrations','m (kg)':'Mass in running order Completed/complete vehicle',
                        'Mt':'WLTP test mass','Enedc (g/km)':'Specific CO2 Emissions (NEDC)','Ewltp (g/km)':'Specific CO2 Emissions (WLTP)',
                        'W (mm)':'Wheel base','At1 (mm)':'Axle width steering axle','At2 (mm)':'Axle width other axle',
                        'Ft':'Fuel type','Fm':'Fuel mode','ec (cm3)':'Engine capacity',
                        'ep (KW)':'Engine power','z (Wh/km)':'Electric energy consumption','IT':'Innovative technology or group of innovative technologies',
                        'Ernedc (g/km)':'Emissions reduction through innovative technologies (NEDC)','Erwltp (g/km)':'Emissions reduction through innovative technologies (WLTP)','De':'Deviation factor',
                        'Vf':'Verification factor','Status':'Provision or Final','year':'Reporting year',
                        'Date of registration':'Date of registration','Fuel consumption ':'Fuel consumption','ech':'ech',
                        'RLFI':'Roadload (Matrix) family identifier','Electric range (km)':'Electric range (km)'})